### ISSUE TITLE
Triangles in the Menu

### ISSUE THREAD

**Issue by HDValentin** [elmastudio/aino-theme#142]
I have small triangels in the top of the main menu. See Screenshot.
Address: https://happy-heidelberg.de/

![Zwischenablage01](https://user-images.githubusercontent.com/1276955/99193099-085f8000-2777-11eb-80c5-b1728a18f182.jpg)

**Comment by ellenbauer** [comment]
Hi there,

yes, I can see that as well. Could you check your cache and clear it once and also check, if you have the latest theme version (currently) 1.2.4 running. The theme version doesn't seem to be the current one, since we changed the design of the description text.

If this doesn't help, please let me know.

Thanks so much,
Ellen

**Comment by HDValentin** [comment]
Yes looks better after clearing the cache.
